export const GET_LIST_FILM = "GET_LIST_FILM";
export const RESET_LIST_FILM = "RESET_LIST_FILM";
export const LOADING_LIST_FILM = "LOADING_LIST_FILM";
export const DELETE_LIST_FILM = "DELETE_LIST_FILM"