export const GET_PROMOTE = "GET_PROMOTE"

export const GET_MOST_VIEW = "GET_MOST_VIEW";

export const GET_LATEST = "GET_LATEST";

export const UPDATE_HOMEPAGE_SAVED_FILM = "UPDATE_HOMEPAGE_SAVED_FILM";