export const GET_FILM = "GET_FILM";


export const GET_ACTOR_INTRO = "GET_ACTOR_INTRO";

export const GET_COMMENT = "GET_COMMENT";

export const GET_FILM_BY_DIFFICULT = "GET_FILM_BY_DIFFICULT";

export const IS_REVIEWED = "IS_REVIEWED";

export const LOADING_REVIEWD = "LOADING_REVIEWD";