const res = {
    // ic_more: require('./Icons/ic_more.png'),
    // green_star: require('./Icons/green-star.png'),
    // purple_chart: require('./Icons/purple-chart.png'),
    // ic_like: require('./Icons/ic_like.png'),
    // ic_like_blue: require('./Icons/ic_like_blue.png'),
    // banner_film: require('./Images/ghost_in_shell.png'),
    // //avatars
    // ava1: require('./Avatars/ava1.png'),
    // ava2: require('./Avatars/ava2.png'),
    // ava3: require('./Avatars/ava3.png'),



    icons: {
        search: require('./Icons/ic_search.png'),
        menu: require('./Icons/ic_menu.png'),
        moreArrow: require('./Icons/ic_more_arrow.png'),
        moreDot: require('./Icons/ic_more.png'),
        bookmark: require('./Icons/ic_bookmark.png'),
        bookmarkFull: require('./Icons/ic_bookmark_full.png'),
        error: require('./Icons/ic_error.png'),
        send: require('./Icons/ic_send.png'),
        like: require('./Icons/ic_like.png'),
        close: require('./Icons/ic_close.png'),
        comment: require('./Icons/ic_comment.png'),
        quiz: require('./Icons/ic_quiz.png'),
        volcabulary: require('./Icons/ic_volcabulary.png'),
        play: require('./Icons/ic_play.png'),
        pause: require('./Icons/ic_pause.png'),
        back: require('./Icons/ic_back.png'),
        favorite: require('./Icons/ic_favorite_empty.png'),
        favoriteFull: require('./Icons/ic_favorite_full.png'),
        rating: require('./Icons/ic_rating_empty.png'),
        ratingFull: require('./Icons/ic_rating_full.png'),
        backSec: require('./Icons/ic_back_10_sec.png'),
        forwardSec: require('./Icons/ic_forward_10_sec.png'),
        volume: require('./Icons/ic_volume.png'),
        expand: require('./Icons/ic_expand.png'),
        collapse: require('./Icons/ic_collapse.png'),
        filmType: require('./Icons/ic_box.png'),
        level: require('./Icons/ic_level.png'),
        tip: require('./Icons/ic_tip.png'),
        search: require('./Icons/ic_search.png'),
        history: require('./Icons/ic_history.png'),
        bookmarks: require('./Icons/ic_bookmarks.png'),
        note: require('./Icons/ic_note.png'),
        feedback: require('./Icons/ic_mail.png'),
        setting: require('./Icons/ic_setting.png'),
        floatingBtn: require('./Icons/btn_play.png'),
        openSubPanel: require('./Icons/ic_sub_panel_close.png'),
        circle: require('./Icons/ic_circle.png'),
        circleFull: require('./Icons/ic_circle_full.png'),
        profile: require('./Icons/ic_profile.png'),
        password: require('./Icons/ic_password.png'),
        add: require('./Icons/ic_add.png'),
        camera: require('./Icons/ic_camera.png'),
    },
    images: {
        default: require('./Images/img_default.png'),
        avatar: require('./Images/img_avatar.png'),
        notFound: require('./Images/img_not_found.png'),
        logo_full: require('./Images/logo_full.png'),
        success: require('./Images/img_success.png'),
        congrats: require('./Images/img_congrats.png'),
        login_background: [
            require('./Images/login_1.png'),
            require('./Images/login_2.png'),
        ]
    },
    colors: {
        background: '#fafafa',
        homePageBackground: '#F5F5F5',
        subtitle: '#757575',
        body: '#9e9e9e',
        blue: '#64B5F6',
        pink: '#E91E63',
        violet: '#AB47BC',
        yellow: '#FFC107',
        red: '#f44336',
        line: '#E0E0E0',
        gray: '#9E9E9E',
        lightgray: '#E0E0E0',
        filmSubBackground: '#424242',

        //level's colors
        levelEasy: '#009688',
        levelMedium: '#AB47BC',
        levelHard: '#E91E63',

        volcabularyColors: [
            '#64B5F6',
            '#E91E63',
            '#AB47BC',
            '#FFC107',
            '#9E9E9E'
        ]
    },
    fonts: {
        common: 'sans-serif',
        light: 'sans-serif-light',
    },
    animations: {
        check: require('./Animations/check.gif'),
    },
    // video: {
    //     test: require('./Videos/test.mp4'),
    // },
    ratio: 9 / 16,
}
export default res;