# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifiuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'user/avatar/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(upload_to=b'film/thumbnail/'),
        ),
    ]
