# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0003_auto_20171021_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('profile_image', models.ImageField(upload_to=b'actor/profile_image')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=254)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.CharField(max_length=255)),
                ('sub', models.FileField(upload_to=b'episode/sub/')),
                ('thumbnail', models.ImageField(upload_to=b'episode/thumbnail/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmBelongToType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Type')),
            ],
        ),
        migrations.CreateModel(
            name='FilmHasActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Actor')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSaveFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSaveVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.FifiUser')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=500)),
                ('meaning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersavevocabulary',
            name='vocabulary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Vocabulary'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quizz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifistudy_api.Quizz'),
        ),
    ]
