# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0008_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
