# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0009_auto_20171025_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
