# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0010_comment_like_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifiuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Inactive'), (1, b'Active')], default=0),
        ),
    ]
