# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0016_auto_20171031_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='episode',
            name='eng_sub',
            field=models.FileField(blank=True, null=True, upload_to=b'episode/eng_sub/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='vie_sub',
            field=models.FileField(blank=True, null=True, upload_to=b'episode/vie_sub/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
