# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0018_auto_20171116_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
