# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0020_auto_20171126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b'episode/video/'),
        ),
    ]
