# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifistudy_api', '0021_auto_20171212_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile_image_240',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'actor/profile_image_240/'),
        ),
        migrations.AddField(
            model_name='film',
            name='thumbnail240',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'film/thumbnail240/'),
        ),
    ]
