import res from '../Resources/index.js';

export default ObjComment = [
    {
        id: 1,
        avatar: 'https://shop.r10s.jp/amiami/cabinet/images/2016/08/goods-00075698.jpg',
        user_id: 'uid1',
        user_name: 'user 1',
        first_name: 'Ranpo',
        last_name: 'Edogawa',
        content: 'bộ phim này rất hay, mong ad cập nhật thêm nhé ! This Tv show is so interesting! , I hope you update more ! ',
        like_number: 23,
        is_liked: false,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 2,
        avatar: 'https://pbs.twimg.com/profile_images/872443539497594880/JbHsgedd_400x400.jpg',
        user_id: 'uid2',
        user_name: 'user 2',
        first_name: 'Emma',
        last_name: '',
        content: 'bài hát quá hay..lắc lư ',
        like_number: 21,
        is_liked: true,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 3,
        avatar: 'https://i.pinimg.com/564x/e7/74/a7/e774a7d57ec747dc2bb6ed7186c5b42e.jpg',
        user_id: 'uid3',
        user_name: 'user 3',
        first_name: 'victorique',
        last_name: 'de blois',
        content: 'các bạn ơi! Sao hình ảnh không nét nhỉ? Hay do máy của mình... Cách chỉnh hình ảnh nét thì phải làm sao ạ? ',
        like_number: 20,
        is_liked: false,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 4,
        avatar: 'https://loveisbeautyfullpain2015.files.wordpress.com/2016/07/jyk.jpg?w=620',
        user_id: 'uid3',
        user_name: 'user 3',
        first_name: 'Osamu',
        last_name: 'Dazai',
        content: ':D phim rất hay, tjks anh chị admin ạ :p ',
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
        like_number: 20,
        is_liked: true,
    },
    {
        id: 5,
        is_liked: true,
        username: 'phuongnl',
        avatar: 'https://vignette.wikia.nocookie.net/csydes-test/images/6/6b/%28AnimeFreak%29_Mirai_Kuriyama.png/revision/latest?cb=20170404065736',
        first_name: 'Mirai',
        last_name: 'Kuriyama',
        content: 'can u guys plz fix this ???? the subtitles are not right with the sounds and also the videos from episode 15 ->20. Thank advance',
        like_number: 3,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
        userId: 1,
        filmId: 2,
    }
]


//     export default ObjComment = {
//     id: 5,
//     is_liked: false,
//     username: "phuong",
//     avatar: "https://vignette.wikia.nocookie.net/csydes-test/images/6/6b/%28AnimeFreak%29_Mirai_Kuriyama.png/revision/latest?cb=20170404065736",
//     first_name: "Umino",
//     last_name: "San",
//     content: "nqgw8o;gwaoptmkca",
//     like_number: 10,
//     created_at: "2017-11-22T02:14:11.777000Z",
//     updated_at: "2017-11-22T02:14:11.777000Z",
//     user_id: 1,
//     film_id: 1
// }